#!/bin/bash

# Create the file containing the PID
echo $$ > /var/run/myscript.pid

# Define the signal handlers
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display the message indefinitely
echo "To infinity and beyond..."
while true; do
  sleep 1
done
