#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name, of processes whose name contain the word bash
for pid in $pids
do
process_name=$(cat /proc/$pid/cmdline | tr '\0' ' ')
echo "PID: $pid, Process Name: $process_name"
done
