#!/usr/bin/env bash
# Print 10 times Holberton School with until Loop
#when it reaches9 it prints hi best school

i=0
while [$i -gt 9]
do
	echo "Best School"
	if [ $i=9 ]
	then
	echo "Best School/n"
	echo "Hi"
	fi
done
i=$i
