#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp/etc/hosts/new.hosts
sed -i 's/127.0.0.1/127.0.0.2/' new.hosts
sed -i '2i8.8.8.8 facebook.com' new.hosts
cp -f /new.hosts /etc/hosts
